#:kivy 1.10.0

# Set rules for custom classes

# gi GUI (root widget, BoxLayout)
<testGUI>:
    orientation: 'vertical'  # property
    TextInput:  # Child1
        id: my_textinput
        font_size: 150
        size_hint_y: None
        height: 200
        text: 'default'
        on_text: root.change_label_color()  # on text change (works for all
                                            # proerties) call function defined
                                            # in .py
                                            # root is here giGUI (the highes
                                            # level widget), alternatively
                                            # specify with widget name
                 # Alternative: import python module here:
                 # #:import local_name module_name
                 # Then define on_text:
                 # my_label.color = [random.random() for i in xrange(3)] + [1]
    FloatLayout:  #Child2
        Scatter:  #Child2's child1
            Label:
                id: my_label
                text: my_textinput.text  # bind() text o text_input to label
                font_size: 150
                color: root.text_color  # access property from python root widget
    BoxLayout:
        size_hint_y: None
        height: 150
        Label:
            id: label1
            text: my_textinput.text[:3][::-1]
            font_size: 100
            color: root.text_color  # access property from python root widget
        Label:
            id: label2
            text: my_textinput.text[:3][::-1]
            font_size: 100
            color: root.text_color  # access property from python root widget